### PR TITLE
Switch to async search pipeline processing.

### PR DESCRIPTION
**Pull request by austintlee**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[issue](https://github.com/opensearch-project/OpenSearch/issues/10248)
 
### Check List
- [ x] New functionality includes testing.
  - [ x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by austintlee** [comment]
This will not build cleanly until the async change in the Search Pipeline itself makes it into "core".

**Comment by HenryL27** [comment]
@austintlee is this PR still alive?

**Comment by ylwu-amzn** [comment]
I think this PR can fix the bug https://github.com/opensearch-project/ml-commons/issues/2334. 
@austintlee Can you rebase and tune this PR ?

**Comment by austintlee** [comment]
@ylwu-amzn Please take a look at a new PR I created to replace this - #2345

**Comment by ylwu-amzn** [comment]
new PR https://github.com/opensearch-project/ml-commons/pull/2345 merged, should we close this PR now ?

**Comment by ylwu-amzn** [comment]
Confirmed with @austintlee , close this PR now

**Pull request closed without merging**
