### PR TITLE
Bump Mockito dependencies

### PR DESCRIPTION
**Pull request by reta**
### Description
Bump Mockito dependencies
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ylwu-amzn** [comment]
LGTM. Just ask, is this to fix CVE or use new feature from newer version of Mockito?

**Review by ylwu-amzn — DISMISSED** [review]

**Comment by reta** [comment]
> LGTM. Just ask, is this to fix CVE or use new feature from newer version of Mockito?

Just Mockito with JDK-21 support :) thanks!

**Comment by dhrubo-os** [comment]
@reta For Java 21, I noticed the following test fails very often:

```
 org.opensearch.ml.rest.RestMLDeployModelActionIT > testReDeployModel FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([85E1F0FBC79317D0]:0)

REPRODUCE WITH: ./gradlew ':opensearch-ml-plugin:integTest' --tests "org.opensearch.ml.rest.RestMLDeployModelActionIT.testReDeployModel" -Dtests.seed=85E1F0FBC79317D0 -Dtests.security.manager=false -Dtests.locale=sr-ME -Dtests.timezone=America/Pangnirtung -Druntime.java=21

org.opensearch.ml.rest.RestMLDeployModelActionIT > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
        at __randomizedtesting.SeedInfo.seed([85E1F0FBC79317D0]:0)
        ```
        
Just wondering if you have any insight on this?

A related PR is : https://github.com/opensearch-project/ml-commons/pull/1598

**Comment by reta** [comment]
> A related PR is : #1598

@dhrubo-os this is interesting, running locally does not hang for me, could you reproduce it?

**Comment by dhrubo-os** [comment]
This is [another PR](https://github.com/opensearch-project/ml-commons/actions/runs/7103955114/job/19337847831?pr=1615) where Java 21 is failing for `testReDeployModel FAILED`

**Comment by reta** [comment]
@dhrubo-os this interesting, I see this exception in GA actions for JDK-17 and JDK-21:

```
 ? ERROR][o.o.m.e.a.r.RemoteModel  ] [integTest-0] Failed to call remote model
?  org.opensearch.OpenSearchStatusException: Error from remote service: {
?    "error": {
?      "message": "Your request contained invalid JSON: 'utf-8' codec can't decode byte 0xeb in position 43: invalid continuation byte",
?      "type": "invalid_request_error",
?      "param": null,
?      "code": null
?    }
```

**Review by Zhangxunmt — APPROVED** [review]

**Review by samuel-oci — APPROVED** [review]

**Review by ylwu-amzn — APPROVED** [review]

**Comment by ylwu-amzn** [comment]
@reta , should we backport this to 2.x branch ? If yes, can you help add `backport 2.x` label and backport to 2.x?

**Comment by reta** [comment]
> @reta , should we backport this to 2.x branch ? If yes, can you help add `backport 2.x` label and backport to 2.x?

Thanks @ylwu-amzn ! Yes, we need to backport but I cannot add labels (only maintainers could do that), sorry about it

**Comment by ylwu-amzn** [comment]
> > @reta , should we backport this to 2.x branch ? If yes, can you help add `backport 2.x` label and backport to 2.x?
> 
> Thanks @ylwu-amzn ! Yes, we need to backport but I cannot add labels (only maintainers could do that), sorry about it

Got it, I added the label. But seems there are some conflicts, you need to backport manually @reta

**Pull request merged**
