### PR TITLE
bump to 1.4.0

### PR DESCRIPTION
**Pull request by ylwu-amzn**
Signed-off-by: Yaliang Wu <ylwu@amazon.com>

### Description
bump to 1.4.0
 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by amitgalitz — APPROVED** [review]

**Comment by ylwu-amzn** [comment]
CI failed 
```
Could not find org.opensearch:common-utils:1.4.0.0-SNAPSHOT.
```

**Comment by ohltyler** [comment]
> > CI failed
> > ```
> > Could not find org.opensearch:common-utils:1.4.0.0-SNAPSHOT.
> > ```
> 
> latest common-utils 1.x commit is version bumped to 1.4, not sure why that is not being made. [opensearch-project/common-utils@b557220](https://github.com/opensearch-project/common-utils/commit/b5572200785971939c3173fe223c473c89f082bd)

I added as part of the manifest in [this PR](https://github.com/opensearch-project/opensearch-build/pull/1825), so not sure. Any idea on next steps / why it wasn't uploaded? @peternied

**Comment by peternied** [comment]
@ohltyler I did a quick look, it seems like 1.4.0's build is failing so these artifacts aren't being published for consumption @opensearch-project/engineering-effectiveness is there someone looking into that?

**Comment by CEHENKLE** [comment]
Hey folks -- there is no 1.4 release.  

We discussed it at the community meeting, followed up in the forums https://discuss.opendistrocommunity.dev/t/2-0-release-date-discussion/8901 for feedback.   Then updated the website https://opensearch.org/blog/partners/2022/02/roadmap-proposal/ and then our public roadmap:  https://github.com/orgs/opensearch-project/projects/1 

Thanks,
/C

**Comment by ohltyler** [comment]
> Hey folks -- there is no 1.4 release.
> 
> We discussed it at the community meeting, followed up in the forums https://discuss.opendistrocommunity.dev/t/2-0-release-date-discussion/8901 for feedback. Then updated the website https://opensearch.org/blog/partners/2022/02/roadmap-proposal/ and then our public roadmap: https://github.com/orgs/opensearch-project/projects/1
> 
> Thanks, /C

Understood, the purpose for doing this is because core OpenSearch and Dashboards had bumped `1.x` branches to `1.4.0` (which makes sense), but then causes all component CIs on `1.x` branches to fail due to version mismatch. So we are trying to bump components to `1.4.0.0` to maintain passing CI on all of the repo branches

**Comment by peternied** [comment]
> Hey folks -- there is no 1.4 release.
> 
> We discussed it at the community meeting, followed up in the forums https://discuss.opendistrocommunity.dev/t/2-0-release-date-discussion/8901 for feedback. Then updated the website https://opensearch.org/blog/partners/2022/02/roadmap-proposal/ and then our public roadmap: https://github.com/orgs/opensearch-project/projects/1
> 
> Thanks, /C

@CEHENKLE Could we update the 1.4.0 release issue with these details?  https://github.com/opensearch-project/opensearch-build/issues/1749  This has been the typical way that our developers have been getting notified about new releases, or in this case I'd recommend using this same channel for *no* release.

**Comment by CEHENKLE** [comment]
@peternied Good call out.  Done.

**Comment by ylwu-amzn** [comment]
> ch makes sense), but then causes all component CIs on `1.x` branches to fail due to version mismatch. So we are trying to bump comp

Agree with Tyler @ohltyler , OpenSearch core has bumped to 1.4 https://github.com/opensearch-project/OpenSearch/pull/2423, we should also follow the version. Will keep this PR open until commons-util 1.4 ready.

**Comment by peternied** [comment]
@ohltyler what do you think about us instead rolling back job-scheduler and common-utils? Seems like that is the root cause of this bad state

**Comment by ohltyler** [comment]
> @ohltyler what do you think about us instead rolling back job-scheduler and common-utils? Seems like that is the root cause of this bad state

I worked on bumping those because of core OpenSearch/Dashboards had bumped to 1.4.0. I believe they should be bumped to follow the current versioning strategy (1.x bumps minor version, 1.3.0 bumps to 1.3.1, etc.), such that after a release, everything is bumped to track a new version in case of a future release at such version.

**Comment by ylwu-amzn** [comment]
Close this PR as we don't have clear decision yet.

**Pull request closed without merging**
