### PR TITLE
[Backport 2661] Add Batch Prediction Mode in the Connector Framework for batch infere…

### PR DESCRIPTION
**Pull request by Zhangxunmt**
Manually backport of https://github.com/opensearch-project/ml-commons/pull/2661

### CODE REVIEW

**Comment by dhrubo-os** [comment]
Original PR has 17 files, but in the backport PR has 19 files... what are we changing here?

**Review by rbhavna — APPROVED** [review]

**Comment by dhrubo-os** [comment]
May be for removing those `System.out..` we should raise a separate PR to maintain consistency between both branches (main, 2.x). Otherwise we will see more & more backport failing in the long run....

**Comment by Zhangxunmt** [comment]
> Original PR has 17 files, but in the backport PR has 19 files... what are we changing here?

Some leftovers System.out.println() from these two files from other PRs when I was cleaning up the code. 

memory/src/test/java/org/opensearch/ml/memory/index/InteractionsIndexTests.java
java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandlerTest.java

**Comment by Zhangxunmt** [comment]
> May be for removing those `System.out..` we should raise a separate PR to maintain consistency between both branches (main, 2.x). Otherwise we will see more & more backport failing in the long run....

Well, this PR is due to the inconsistency from elsewhere between main and 2.x. Since I need to manually backport anyways, let's fix earlier than later. For future changes, they won't need backport if no change in these 2 or 3 files.

**Comment by dhrubo-os** [comment]
> > Original PR has 17 files, but in the backport PR has 19 files... what are we changing here?
> 
> Some leftovers System.out.println() from these two files from other PRs when I was cleaning up the code.
> 
> memory/src/test/java/org/opensearch/ml/memory/index/InteractionsIndexTests.java java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandlerTest.java

Approving this PR assuming that you will raise a PR for main with this clean up code to keep the branch code consistent.

**Review by dhrubo-os — APPROVED** [review]

**Pull request merged**
