### PR TITLE
[Backport 2.x] Fix flaky test of visualization tool (#2416)

### PR DESCRIPTION
**Pull request by Hailong-am**
backport aa09014abdd0a890c9ea3a55bf472ecc7eb7e480 from #2416

### CODE REVIEW

**Review by dhrubo-os — APPROVED** [review]

**Comment by Hailong-am** [comment]
test case failures are related to PredictionITTests, looks like they are flaky also. I have create an issue to track  https://github.com/opensearch-project/ml-commons/issues/2436 and will fix it with another PR.

**Comment by Hailong-am** [comment]
> test case failures are related to PredictionITTests, looks like they are flaky also. I have create an issue to track #2436 and will fix it with another PR.

@ylwu-amzn @dhrubo-os can you help to review https://github.com/opensearch-project/ml-commons/pull/2437 first, this should fix the flaky test of PredictionITTest and get it backport to 2.x, after that i will rebase this backport PR with 2.x

**Review by ylwu-amzn — DISMISSED** [review]

**Comment by ylwu-amzn** [comment]
This PR has conflicts, @Hailong-am Can you fix ?

**Comment by Hailong-am** [comment]
> This PR has conflicts, @Hailong-am Can you fix ?

this may not needed anymore as https://github.com/opensearch-project/ml-commons/pull/2510 fix the undeploy issue. i will close this one.

**Pull request closed without merging**
