### PR TITLE
Add initial search request inference processor

### PR DESCRIPTION
**Pull request by mingshl**
### Description
Add initial search request inference processor
 
### Issues Resolved
https://github.com/opensearch-project/ml-commons/issues/2173
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mingshl** [comment]
Build on linux failed by the flaky test, rerunning linux test

```
REPRODUCE WITH: ./gradlew ':opensearch-ml-plugin:integTest' --tests "org.opensearch.ml.rest.RestMLDeployModelActionIT.testReDeployModel" -Dtests.seed=7FCA7B5A34B9F0A0 -Dtests.security.manager=false -Dtests.locale=en-TV -Dtests.timezone=Etc/GMT-4 -Druntime.java=21
    	at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)
    	Locked synchronizers:
    	- java.util.concurrent.ThreadPoolExecutor$Worker@466276d8
```

**Comment by Zhangxunmt** [comment]
I see there are still 16 failed Integ tests. Probably they are not flaky tests any more. It may be just 1 error causing all these failures.

Tests with failures:
 - org.opensearch.ml.rest.RestMLDeployModelActionIT.testReDeployModel
 - org.opensearch.ml.rest.RestMLDeployModelActionIT.classMethod
 - org.opensearch.ml.rest.RestMLFlowAgentIT.testAgentCatIndexTool
 - org.opensearch.ml.rest.RestMLFlowAgentIT.testAgentSearchIndexTool
 - org.opensearch.ml.rest.RestMLGetTaskActionIT.testGetTaskAPI_Success
 - org.opensearch.ml.rest.RestMLInferenceIngestProcessorIT.testMLInferenceProcessorLocalModelNestedField
 - org.opensearch.ml.rest.RestMLInferenceIngestProcessorIT.classMethod
 - org.opensearch.ml.rest.RestMLInferenceSearchRequestProcessorIT.testMLInferenceProcessorLocalModel
 - org.opensearch.ml.rest.RestMLInferenceSearchRequestProcessorIT.testMLInferenceProcessorRemoteModelRewriteQueryType
 - org.opensearch.ml.rest.RestMLMemoryCircuitBreakerIT.testRunWithMemoryCircuitBreaker
 - org.opensearch.ml.rest.RestMLRAGSearchProcessorIT.testBM25WithBedrockWithConversation
 - org.opensearch.ml.rest.RestMLRAGSearchProcessorIT.testBM25WithBedrock
 - org.opensearch.ml.rest.RestMLSearchModelActionIT.testSearchModelAPI_Success

 - org.opensearch.ml.rest.RestMLTrainAndPredictIT.testTrainAndPredictKmeans
 - org.opensearch.ml.tools.VisualizationsToolIT.testVisualizationFound
 - org.opensearch.ml.tools.VisualizationsToolIT.testVisualizationNotFound

**Comment by mingshl** [comment]
> I see there are still 16 failed Integ tests. Probably they are not flaky tests any more. It may be just 1 error causing all these failures. Please check the CI for Linux in the test summary. 
> 
> 
> 
> 

The windows CI passed. Only the Linux CI is failing

**Comment by mingshl** [comment]
IT test failed due to timeout limit, retrying CI

**Review by b4sjoo — APPROVED** [review]

**Review by Zhangxunmt — APPROVED** [review]

**Comment by Zhangxunmt** [comment]
approved. But to be on the safe side, let's wait for the CI pass before merging. It should pass if it's only flaky.

**Comment by mingshl** [comment]
Still facing the timeout issue in CI
```
org.opensearch.ml.rest.RestMLDeployModelActionIT > testReDeployModel STANDARD_ERROR
    ???? 24, 2024 1:48:23 ?.?. com.carrotsearch.randomizedtesting.ThreadLeakControl$2 evaluate
    WARNING: Suite execution timed out: org.opensearch.ml.rest.RestMLDeployModelActionIT
    ==== jstack at approximately timeout time ====```
    
Cannot reproduce locally. Local run IT success.

**Comment by mingshl** [comment]
will merge this PR and will watch if this timeout issue is happening to other PRs as well.

**Pull request merged**
