### PR TITLE
change auto redeploy enabled setting to true

### PR DESCRIPTION
**Pull request by rbhavna**
### Description
change auto redeploy enabled setting to true
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dhrubo-os** [comment]
Let's add more details (if possible) in the issue description on why we want to
change auto redeploy enabled setting to true now?

**Comment by ylwu-amzn** [comment]
Let's hold this PR for now, Dylan has some suggestion for enhancing this feature.

**Review by jngz-es — APPROVED** [review]

**Comment by austintlee** [comment]
Wouldn't this be a breaking change?

**Comment by ylwu-amzn** [comment]
> Wouldn't this be a breaking change?

I think that depends on how to understand breaking. The model auto redeploy won't break predict API. But if user don't know this, they may feel confused why the model auto redeployed now. It won't break anything, but just have some unexpected auto redeployed models.

**Comment by ylwu-amzn** [comment]
Will close this PR as we don't plan to open this.

**Pull request closed without merging**
