### PR TITLE
Fix: switch case bug due to JAVA 11

### PR DESCRIPTION
**Pull request by yuye-aws**
### Description
Fix switch case bug due to JAVA 11

### Related Issues
Resolves CI error in https://github.com/opensearch-project/ml-commons/actions/runs/10344573259/job/28630322124?pr=2821

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by yuye-aws** [comment]
The CI error is weird. I cannot reproduce it locally. Can someone please help rerun the tests?

**Comment by yuye-aws** [comment]
@dhrubo-os can you help review this PR?

**Comment by dhrubo-os** [comment]
We need this in Main branch too.

May be you can raise the PR in Main first, and then backport altogether in 2.x?

**Comment by yuye-aws** [comment]
> We need this in Main branch too. We don't want to diverge the code between main vs 2.x branch.
> 
> May be you can raise the PR in Main first, and then backport altogether in 2.x?

I see.

**Comment by yuye-aws** [comment]
Rebased main branch and reopen this PR

**Comment by yuye-aws** [comment]
@dhrubo-os CI get passed. Can you review?

**Review by dhrubo-os — APPROVED** [review]

**Review by xinyual — APPROVED** [review]

**Pull request merged**
