### PR TITLE
Fix duplicate trace records

### LINKED ISSUE #1968: [BUG] Duplicate trace record
**What is the bug?**
Run `MLChatAgent` and check all the trace records in `.plugins-ml-memory-message` index, there will have two trace records with same content for final answer.

An example response, you can see trace with number 6 and 7 are duplicate
```json
[
    {
        "interactionId": "x95uXo0BGVYn19hhheIJ",
        "input": "can you show me the visualization of sales",
        "output": "Now I know how to respond",
        "createTime": "2024-01-31T07:31:57.832292374Z",
        "origin": null,
        "traceNumber": 1
    },
    {
        "interactionId": "yN5uXo0BGVYn19hhheIX",
        "input": "sales",
        "output": "Title,Id\n[eCommerce] Sales by Category,37cc8650-b882-11e8-a6d9-e546fe2bba5f\n[eCommerce] Sales by Gender,ed8436b0-b88b-11e8-a6d9-e546fe2bba5f\n[eCommerce] Average Sales Price,4b3ec120-b892-11e8-a6d9-e546fe2bba5f\n",
        "createTime": "2024-01-31T07:31:57.841167178Z",
        "origin": "VisualizationTool",
        "traceNumber": 2
    },
    {
        "interactionId": "zN5uXo0BGVYn19hhi-L7",
        "input": "can you show me the visualization of sales",
        "output": "Based on the visualizations provided, it seems the [eCommerce] Sales by Category visualization would be most relevant to understand sales breakdown by category.",
        "createTime": "2024-01-31T07:31:59.610137456Z",
        "origin": null,
        "traceNumber": 3
    },
    {
        "interactionId": "zd5uXo0BGVYn19hhi-L_",
        "input": "[eCommerce] Sales by Category",
        "output": "Title,Id\n[eCommerce] Sales by Category,37cc8650-b882-11e8-a6d9-e546fe2bba5f\n[eCommerce] Sales by Gender,ed8436b0-b88b-11e8-a6d9-e546fe2bba5f\n[eCommerce] Average Sales Price,4b3ec120-b892-11e8-a6d9-e546fe2bba5f\n",
        "createTime": "2024-01-31T07:31:59.614597716Z",
        "origin": "VisualizationTool",
        "traceNumber": 4
    },
    {
        "interactionId": "0N5uXo0BGVYn19hhl-Ia",
        "input": "can you show me the visualization of sales",
        "output": "Now I know the final answer",
        "createTime": "2024-01-31T07:32:02.45740304Z",
        "origin": null,
        "traceNumber": 5
    },
    {
        "interactionId": "z95uXo0BGVYn19hhl-Ia",
        "input": "can you show me the visualization of sales",
        "output": "To see the visualization of sales you had requested, one of the available visualizations was shown containing metrics like sales by category, sales by gender, and average sales price for the day.",
        "createTime": "2024-01-31T07:32:02.457582962Z",
        "origin": null,
        "traceNumber": 6
    },
    {
        "interactionId": "zt5uXo0BGVYn19hhl-Ia",
        "input": "can you show me the visualization of sales",
        "output": "To see the visualization of sales you had requested, one of the available visualizations was shown containing metrics like sales by category, sales by gender, and average sales price for the day.",
        "createTime": "2024-01-31T07:32:02.457707056Z",
        "origin": null,
        "traceNumber": 7
    }
]
```

**How can one reproduce the bug?**

**What is the expected behavior?**
should not have duplicate trace records

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Looks like this code are duplicate 
https://github.com/opensearch-project/ml-commons/blob/main/ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java#L377-L405

### PR DESCRIPTION
**Pull request by Hailong-am**
### Description
Fix duplicate trace records for final answer step
 
### Issues Resolved
#1968 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Hailong-am** [comment]
@jngz-es @dhrubo-os this should be a code merge issue, we have duplicate code for saving trace of final answer, please help to take a look

**Review by ylwu-amzn — APPROVED** [review]

**Comment by ylwu-amzn** [comment]
Seems duplicate TT https://github.com/opensearch-project/ml-commons/pull/1973

**Comment by Hailong-am** [comment]
> Seems duplicate with https://github.com/opensearch-project/ml-commons/pull/1973

Yes We can close this one

**Comment by ylwu-amzn** [comment]
@Hailong-am feel free to include this file change `ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java` in your next PR

**Pull request closed without merging**
