### PR TITLE
enhance connector helper notebook to support 2.9

### PR DESCRIPTION
**Pull request by ylwu-amzn**
### Description
enhance connector helper notebook to support 2.9
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by rbhavna — APPROVED** [review]

**Review by Zhangxunmt — APPROVED** [review]
This works. But given that it applies to newer versions after 2.9, my concern is that it makes people think this "model_group" is totally a "chicken rib" because it shares the name with model name. And model name is mostly unique so it ends up with unique model name with a dedicated model group.

**Comment by ylwu-amzn** [comment]
>   And model name is mostly unique so it ends up with unique model name with a dedicated model group.

Model group name is unique, but model name not. One model group can have multiple models with same model name.

**Comment by minalsha** [comment]
@ylwu-amzn why do we need to have this when we have Flow framework which exactly does this right now?

**Comment by ylwu-amzn** [comment]
> @ylwu-amzn why do we need to have this when we have Flow framework which exactly does this right now?

But we don't have flow framework on AWS now, right ? This is to help current AWS cx

**Pull request merged**
