### PR TITLE
Added missing result filter to inference

### LINKED ISSUE #2366: [BUG] asymmetric model inference ignores `ModelResultFilter`
**What is the bug?**
There is a small bug in the `TextEmbeddingModel` class in relation with the new asymmetric model support. In the method `addPrefixesToData`, that is only called when an asymmetric model is used, I forgot to add the existing result filter to the new instance of the `TextDocsInputDataSet` that is created with the corresponding prefixes.

I noticed the issue while working on https://github.com/opensearch-project/neural-search/pull/710.

**How can one reproduce the bug?**
1. run inference on an asymmetric model using a result filter
2. see that the result filter will not be applied

**What is the expected behavior?**
The result filter should be applied.

**What is your host/environment?**
 - OS: all

**Do you have any screenshots?**
N.a.

**Do you have any additional context?**
I have a fix and will open a PR immediately.

### PR DESCRIPTION
**Pull request by br3no**
### Description
The missing result filter is added to the code path where it was forgotten in an earlier PR.
 
### Issues Resolved
#2366
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by br3no** [comment]
@dhrubo-os @ylwu-amzn, this is related to the PR of earlier this week (#2318).

I'm sorry about this back-and-forth. The fact that the feature is spread across ml-commons and neural-search makes things a bit more involved.

I'm pretty confident though, that this is the last piece missing. I was able to test all changes in combination end-to-end today (this is how the bug surfaced).

**Review by ylwu-amzn — APPROVED** [review]

**Review by mingshl — APPROVED** [review]

**Review by dhrubo-os — APPROVED** [review]

**Comment by ylwu-amzn** [comment]
@br3no , I see you have contributed several PRs to ml-commons repo. Really appreciate your contribution. Considering that, do you mind to become a maintainer of ml-commons repo?

**Comment by br3no** [comment]
@ylwu-amzn I'm flattered. 😉

Let me think about this and come back to you.

**Comment by br3no** [comment]
@ylwu-amzn I'm in. Let me know what the next steps are.

**Pull request merged**
