### PR TITLE
Add accessUserInformation to the plugin security policy.  (Issue # 844)

### LINKED ISSUE #844: [BUG]Model content hash can't match original hash value
**What is the bug?**
`Model content hash can't match original hash value`

**How can one reproduce the bug?**

I tried with the current code base. I executed the command `./gradlew run` to test.

1. First I upload the model

```
POST /_plugins/_ml/models/_upload
{
  "name": "huggingface/sentence-transformers/all-MiniLM-L12-v2",
  "version": "1.0.1",
  "model_format": "TORCH_SCRIPT"
}
```

2. Then Load the model in memory. This time it works fine. `http://localhost:9200/_plugins/_ml/models/l-bnSYcBQg5VYC5uIxWy/_load`

3. I also generated the embedding with the loaded model and it works fine.

4. Now I unload the model: `http://localhost:9200/_plugins/_ml/models/l-bnSYcBQg5VYC5uIxWy/_unload`
5. And now I try to deploy again. Then I face the error: 

```
[2023-04-03T18:42:42,801][ERROR][o.o.m.m.MLModelManager   ] [integTest-0] Model content hash can't match original hash value
[2023-04-03T18:42:42,804][ERROR][o.o.m.a.f.TransportForwardAction] [integTest-0] deploy model failed on all nodes, model id: l-bnSYcBQg5VYC5uIxWy
[2023-04-03T18:42:42,804][INFO ][o.o.m.a.f.TransportForwardAction] [integTest-0] deploy model done with state: DEPLOY_FAILED, model id: l-bnSYcBQg5VYC5uIxWy
[2023-04-03T18:42:42,804][INFO ][o.o.m.a.d.TransportDeployModelOnNodeAction] [integTest-0] deploy model task done m-buSYcBQg5VYC5uMhUu

```

**What is the expected behavior?**
Model should load again.

**What is your host/environment?**
 - Version [e.g. 2.7]
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by austintlee**
### Description
Fixes an issue where zip files in model_cache are not getting deleted.
 
### Issues Resolved
#844 
 
### Check List
- [ ] New functionality includes testing.
  - [x ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dhrubo-os** [comment]
Awesome!! If you think the issue is resolved, can we remove this check [here](https://github.com/opensearch-project/ml-commons/blob/main/plugin/src/test/java/org/opensearch/ml/rest/RestMLDeployModelActionIT.java#L31)?

**Comment by austintlee** [comment]
@dhrubo-os I commented it out and the test is passing on my machine (Mac M2):

```
> Task :opensearch-ml-plugin:integTest

org.opensearch.ml.rest.RestMLDeployModelActionIT > testReDeployModel STANDARD_OUT
    [2023-11-05T02:20:47,690][INFO ][o.o.m.r.RestMLDeployModelActionIT] [testReDeployModel] before test
    [2023-11-05T02:20:47,782][INFO ][o.o.m.r.RestMLDeployModelActionIT] [testReDeployModel] initializing REST clients against [http://[::1]:57407, http://127.0.0.1:57408]
    [2023-11-05T02:21:07,048][INFO ][o.o.m.r.RestMLDeployModelActionIT] [testReDeployModel] Re-Deploy model {model_id=qSztnYsBgakGMWcWLqkT, task_type=DEPLOY_MODEL, function_name=TEXT_EMBEDDING, state=CREATED, worker_node=[QWNvoxAmSAmzfjihO8rmzg], create_time=1.699161666982E12, last_update_time=1.699161666982E12, is_async=true}
    [2023-11-05T02:21:07,225][INFO ][o.o.m.r.RestMLDeployModelActionIT] [testReDeployModel] Get Model after re-deploy {name=test_model_name, model_group_id=pyztnYsBgakGMWcWLKnJ, algorithm=TEXT_EMBEDDING, model_version=1, model_format=TORCH_SCRIPT, model_state=DEPLOYED, model_content_size_in_bytes=4554671.0, model_content_hash_value=e13b74006290a9d0f58c1376f9629d4ebc05a0f9385f40db837452b167ae9021, model_config={model_type=bert, embedding_dimension=768.0, framework_type=SENTENCE_TRANSFORMERS}, created_time=1.69916164855E12, last_updated_time=1.699161667177E12, last_registered_time=1.699161650625E12, last_deployed_time=1.699161667176E12, total_chunks=1.0, planning_worker_node_count=1.0, current_worker_node_count=1.0, planning_worker_nodes=[QWNvoxAmSAmzfjihO8rmzg], deploy_to_all_nodes=true}
    [2023-11-05T02:21:07,423][INFO ][o.o.m.r.RestMLDeployModelActionIT] [testReDeployModel] after test
```

**Comment by austintlee** [comment]
@dhrubo-os @zane-neo can you guys take a look?

**Comment by dhrubo-os** [comment]
> @dhrubo-os @zane-neo can you guys take a look?

Looks good to me. I'm not sure why it's showing java 20 test in the workflow as we updated to java 21. Could you please take all the updates from main? Thanks.

**Review by zane-neo — APPROVED** [review]

**Review by ylwu-amzn — APPROVED** [review]

**Pull request merged**
