### PR TITLE
Publish snapshots to maven via GHA (#754)

### PR DESCRIPTION
**Pull request by Zhangxunmt**
### Description
backport the github action maven-publish to main branch to make it runnable.
 
### Issues Resolved
[#734]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ylwu-amzn — APPROVED** [review]

**Comment by MaxKsyunz** [comment]
@gaiksaya could you please have a look at this PR as well?

**Review by gaiksaya — APPROVED** [review]
LGTM! Thanks!

**Review by ylwu-amzn — APPROVED** [review]

**Comment by Yury-Fridlyand** [comment]
@ylwu-amzn @gaiksaya,
I detected a typo in the GHA workflow, so it is not triggered automatically.
Could you please, [run the job](https://github.com/opensearch-project/ml-commons/actions/workflows/maven-publish.yml) manually?

**Comment by gaiksaya** [comment]
Done! Can someone fix the typo?

**Comment by Yury-Fridlyand** [comment]
Will do soon. I see it in multiple repos...

**Comment by Yury-Fridlyand** [comment]
No artifacts were published on [the repo](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch-ml-client/3.0.0.0-SNAPSHOT/) recently. Last update was a week ago.
I suspect credentials were not set or configured correctly.

**Comment by gaiksaya** [comment]
The right path is here @Yury-Fridlyand https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-ml-plugin/3.0.0.0-SNAPSHOT/ (updated today)
As per the [conversation](https://github.com/opensearch-project/ml-commons/pull/754#discussion_r1119231760) @Zhangxunmt was going to add the task to publish jars later on.

**Comment by Yury-Fridlyand** [comment]
Oh, I see. SQL plugin depends on `ml-common` and require jars.

**Comment by gaiksaya** [comment]
@Zhangxunmt @ylwu-amzn ^^

**Pull request merged**
