### PR TITLE
Changing messaging for ILlegalArgumentException on duplicate model gr…

### PR DESCRIPTION
**Pull request by nateynateynate**
…oup creation.

### Description
Updating the error message shown when attempting to create a non-unique model group. 
 
### Issues Resolved
#1290 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ylwu-amzn — DISMISSED** [review]

**Comment by ylwu-amzn** [comment]
Github CI not passing
```
Tests with failures:
 - org.opensearch.ml.model.MLModelGroupManagerTests.test_ModelGroupNameNotUnique
```

Suggest run `./gradlew build` locally first to verify if there is any test failure.

**Review by rbhavna — DISMISSED** [review]

**Comment by nateynateynate** [comment]
Hang on - I've already got `MLModelGroupManagerTests.java` up in my IntelliJ editor. Let me see if I can pull this off for you guys. :-)

**Comment by dhrubo-os** [comment]
@rbhavna do we want this in 2.10 release? If yes can you take care of moving this to 2.10 branch before code freeze? Thanks

**Comment by saratvemulapalli** [comment]
> @rbhavna do we want this in 2.10 release? If yes can you please take care of moving this to 2.10 branch before code freeze? Thanks

Its definitely good customer experience. Lets merge this change.

**Review by saratvemulapalli — APPROVED** [review]

**Review by rbhavna — APPROVED** [review]

**Review by dhrubo-os — APPROVED** [review]

**Pull request merged**
