### PR TITLE
fix Jenkins CI pipeline for OS 3.0 version bump

### PR DESCRIPTION
**Pull request by b4sjoo**
### Description
Jenkins CI workflow on OS 3.0 failed with message:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':opensearch-ml-client:publishShadowPublicationToStagingRepository' (type 'PublishToMavenRepository').
  - Gradle detected a problem with the following location: 'C:\Users\Administrator\AppData\Local\Temp\tmpypnhpv6j\ml-commons\client\build\libs\opensearch-ml-client-3.0.0.0.jar'.
    
    Reason: Task ':opensearch-ml-client:publishShadowPublicationToStagingRepository' uses this output of task ':opensearch-ml-client:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```
https://build.ci.opensearch.org/job/distribution-build-opensearch/7856/console

### Issues Resolved
This is a following up fix on #891 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by jngz-es — APPROVED** [review]

**Review by jngz-es — DISMISSED** [review]

**Review by martin-gaievski — APPROVED** [review]

**Review by jngz-es — APPROVED** [review]

**Review by martin-gaievski — DISMISSED** [review]

**Comment by peterzhuamazon** [comment]
Thanks @b4sjoo can you add a test so that ./gradlew publishAllPublicationsToStagingRepository can be properly tested?

**Comment by b4sjoo** [comment]
Build is failing due to https://github.com/opensearch-project/OpenSearch/pull/7508

**Comment by b4sjoo** [comment]
> Thanks @b4sjoo can you add a test so that ./gradlew publishAllPublicationsToStagingRepository can be properly tested in github checks?

Sure will do. But for now there are more breaking changes to go. We will add them once we saw a success Jenkin build.

**Comment by martin-gaievski** [comment]
@b4sjoo can you please also address call to non-existent method at plugin/src/main/java/org/opensearch/ml/cluster/DiscoveryNodeHelper.java.

Line 41:

```
excludedNodeNames = Strings.commaDelimitedListToSet(ML_COMMONS_EXCLUDE_NODE_NAMES.get(settings));
```
but that method got removed from core:

https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/Strings.java

we detected it in neural-search CI, it's failing due to mentioned call:

https://github.com/opensearch-project/neural-search/actions/runs/5073317788/jobs/9112183832#step:4:149

**Review by rbhavna — APPROVED** [review]

**Comment by b4sjoo** [comment]
This PR fixed the issue #891 and unblock the Jenkins CI from our side.

**Comment by acarbonetto** [comment]
@jngz-es @b4sjoo @rbhavna can someone add the `backport 2.x` label and backport to the 2.x branch please? 
https://github.com/opensearch-project/OpenSearch/pull/8316 was recently merged.

**Comment by b4sjoo** [comment]
@acarbonetto #1018 should unblock SQL team. Are you still facing with a CI block?

**Comment by b4sjoo** [comment]
> @jngz-es @b4sjoo @rbhavna can someone add the `backport 2.x` label and backport to the 2.x branch please? [opensearch-project/OpenSearch#8316](https://github.com/opensearch-project/OpenSearch/pull/8316) was recently merged to 2.x.

This PR is for `String` package refactoring, not `j.u.map` migration.

**Comment by nknize** [comment]
> This PR is for `String` package refactoring, not `j.u.map` migration.

Correct. It looks like ml-commons munged the Strings refactor with the removal of ImmutableOpenMap. We can either tease those apart here in the backport, or we can wait for the Strings refactor PR to be backported to core. The quicker I can get a core reviewer to approve those backport PRs the quicker they will merge. Going the former route will fix the build back to green. Going the latter route will keep the build red until the backport PRs are merged.

**Comment by b4sjoo** [comment]
OK it seems the String refactor backport PR merged.

**Pull request merged**
