### PR TITLE
[Backport 2.x] Read function Name from pretrained model (#1529)

### PR DESCRIPTION
**Pull request by xinyual**
### Description
backport pr for https://github.com/opensearch-project/ml-commons/pull/1529
 
### Issues Resolved
backport pr for https://github.com/opensearch-project/ml-commons/pull/1529
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dhrubo-os — APPROVED** [review]

**Review by zane-neo — APPROVED** [review]

**Comment by ylwu-amzn** [comment]
Make the commit message more readable 
`[Backport 2.x] Read function Name from pretrained model (#1529)` ?

**Comment by ylwu-amzn** [comment]
After merging 2.11 backport PR, the commit history is not readable https://github.com/opensearch-project/ml-commons/commits/2.11
From the message `backport to 2.11`, it's hard to tell what's this commit for.

Screenshot 2023-11-14 at 5 30 46 PM

**Comment by xinyual** [comment]
> Make the commit message more readable `[Backport 2.x] Read function Name from pretrained model (#1529)` ?

Ok. Will do so. Sorry for the mistake.

**Comment by xinyual** [comment]
Force push to make commit readable.

**Pull request merged**
