### PR TITLE
Bumping version to 2.11.1.0

### PR DESCRIPTION
**Pull request by dhrubo-os**
### Description
[release note for 2.11.1.0]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ylwu-amzn** [comment]
Have you bumped version to 2.11.1 in 2.11 branch?

**Comment by ylwu-amzn** [comment]
> Have you bumped version to 2.11.1 in 2.11 branch?

Never minde, I see you bumped version in this PR. Suggest use different PRs for version bumping and release notes

**Comment by dhrubo-os** [comment]
> > Have you bumped version to 2.11.1 in 2.11 branch?
> 
> Never mind, I see you bumped version in this PR. Suggest use different PRs for version bumping and release notes

Sure, done.

**Review by ylwu-amzn — APPROVED** [review]
common-utils 2.11.1 not ready yet. Approve to unblock

**Review by b4sjoo — APPROVED** [review]

**Pull request merged**
